Trailhead Tracker/src/objects/Daily_Stats__c.object
<CustomObject>
    <description>This object stores the badges, points, trails, ranks of the trailhead user every day to obtain the progression of the team member over time. It has a Master-Detail relationship with the Trailhead User object.</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>This field stores the date to which the stats belong.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trailhead_User__c</fullName>
        <description>This field is stores the reference to the master Trailhead user record.</description>
        <label>Trailhead User</label>
        <referenceTo>Trailhead_User__c</referenceTo>
        <relationshipLabel>Daily Stats</relationshipLabel>
        <relationshipName>Daily_Stats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Daily Stats</label>
    <nameField>
        <displayFormat>S-{0000000000}</displayFormat>
        <label>Daily Stats Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Trailhead Tracker/src/objects/Trailhead_User__c.object
<CustomObject>
    <description>This object stores the details of the team members who uses the application. Whenever a user signs up to the system via the public page, this object stores that record.</description>
    <fields>
        <fullName>Skills__c</fullName>
        <description>Stores the skills from Trailhead in JSON format</description>
        <label>Skills</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Streak_Updated__c</fullName>
        <description>Stores the Date when the streak count was last updated</description>
        <label>Streak Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Streak__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Stores the user&apos;s streak (the number of consecutive days the user completed the challenge)</description>
        <label>Streak</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trailhead_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field stores the Trailhead Id available on the user’s Trailhead profile page. This is the only data required for the user to sign up for the application.</description>
        <label>Trailhead Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Trailhead User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailhead Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trailhead Tracker/src/classes/BatchToUpdateTrailheadStats.cls
/*
* Trailhead Tracker Application
* Shashwat Nandan
* 28/1/2019
*/
global class BatchToUpdateTrailheadStats implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    global final String query;
    global final Date dateToday;
    
    global BatchToUpdateTrailheadStats(){
        dateToday = Date.today();
        query='Select Trailhead_Id__c, Streak__c, Streak_Updated__c, Skills__c from Trailhead_User__c';
    }
    
    global Database.QueryLocator start(Database.BatchableContext bC){
        
        List<Daily_Stats__c> dailyStatsList = [Select Id from Daily_Stats__c where Date__c =: dateToday];
        Database.DeleteResult[] sr = Database.delete(dailyStatsList, false);
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bC, List<sObject> scopeList){
        
        List<String> trailheadUserIds = new  List<String>();
        List<String> trailheadUserTrailheadIds = new  List<String>();
        Map<Id, Trailhead_User__c> mapIdTrailheadUser = new   Map<Id, Trailhead_User__c>();
        for(sobject scope : scopeList)
        {
            Trailhead_User__c trailheadUser = (Trailhead_User__c) scope;
            trailheadUserIds.add(trailheadUser.Id);
            trailheadUserTrailheadIds.add(trailheadUser.Trailhead_Id__c);
            mapIdTrailheadUser.put(trailheadUser.Id, trailheadUser);
        }
        TrailheadTrackerHelper.saveTrailheadStats(trailheadUserIds, trailheadUserTrailheadIds, mapIdTrailheadUser);
    }
    
    global void finish(Database.BatchableContext bC){
        system.debug('Batch Completed');
        List<AsyncApexJob> batchJobsListRaw = [SELECT CreatedDate, Status, ExtendedStatus, TotalJobItems, NumberOfErrors FROM AsyncApexJob where ApexClass.Name = 'BatchToUpdateTrailheadStats' ORDER BY CreatedDate DESC LIMIT 1];
        if(batchJobsListRaw != null && !batchJobsListRaw.isEmpty() )
        {
            AsyncApexJob latestBatchJob = batchJobsListRaw.get(0);
            if(latestBatchJob.NumberOfErrors > 0 /*&& latestBatchJob.ExtendedStatus.containsIgnoreCase('Read timed out')*/)
            {
                system.debug('Batch Failed. Re-Running');
                BatchToUpdateTrailheadStats batchToUpdateTrailheadStats= new BatchToUpdateTrailheadStats(); 
                database.executebatch(batchToUpdateTrailheadStats, 1);
            }
        }
    }
}