Trailhead Tracker/src/objects/Trailhead_User__c.object
<CustomObject>
    <description>This object stores the details of the team members who uses the application. Whenever a user signs up to the system via the public page, this object stores that record.</description>
    <fields>
        <fullName>Skills__c</fullName>
        <description>Stores the skills from Trailhead in JSON format</description>
        <label>Skills</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Streak_Updated__c</fullName>
        <description>Stores the Date when the streak count was last updated</description>
        <label>Streak Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Streak__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Stores the user&apos;s streak (the number of consecutive days the user completed the challenge)</description>
        <label>Streak</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trailhead_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field stores the Trailhead Id available on the user’s Trailhead profile page. This is the only data required for the user to sign up for the application.</description>
        <label>Trailhead Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Trailhead User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailhead Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trailhead Tracker/src/classes/TrailheadUserTriggerHelper.cls
public class TrailheadUserTriggerHelper {
    
    public static void triggerHelper()
    {
        if(trigger.isAfter)
        {
            if(trigger.isInsert)
            {
                TrailheadUserTriggerHelper.afterInsert(trigger.new);
            }
        }
    }
    
    public static void afterInsert(List<Trailhead_User__c> triggerNew)
    {
        //save trailhead stats for today
        TrailheadUserTriggerHelper.initSaveDailyStats(trigger.new);
    }
    public static void initSaveDailyStats(List<Trailhead_User__c> triggerNew)
    {
        List<Id> trailheadUserIds = new  List<Id>();
        
        for(Trailhead_User__c trailheadUser : triggerNew) 
        {
            trailheadUserIds.add(trailheadUser.Id);
        }
        saveDailyStats(trailheadUserIds);
    }
    
    @Future(callout=true)	
    public static void saveDailyStats(List<Id> trailheadUserIdsList)
    {
        List<String> trailheadUserIds = new  List<String>();
        List<String> trailheadUserTrailheadIds = new  List<String>();
        Map<Id, Trailhead_User__c> mapIdTrailheadUser = new   Map<Id, Trailhead_User__c>();
        for(Trailhead_User__c trailheadUser : [Select Trailhead_Id__c, Streak__c, Streak_Updated__c, Skills__c from Trailhead_User__c where Id in :trailheadUserIdsList])
        {
            trailheadUserIds.add(trailheadUser.Id);
            trailheadUserTrailheadIds.add(trailheadUser.Trailhead_Id__c);
            mapIdTrailheadUser.put(trailheadUser.Id, trailheadUser);
        }
        TrailheadTrackerHelper.saveTrailheadStats(trailheadUserIds, trailheadUserTrailheadIds, mapIdTrailheadUser);
    }
}